### ISSUE TITLE
MySQL - Table not created - os_groups_membership

### ISSUE THREAD

**Issue by AsaTyr2018** [diva/d2#41]
Good day,
i just installed the latest diva repo r09110 and ran into an issue.
once i try to sign in throw a compatible viewer (firestorm) the loading process hangs up on 50%
while the console gives out the message that a mysql table "os_groups_membership" doesn´t exist.

**Error Message:**
```
UseCircuitCode handling from endpoint xxx.xxx.xxx.xxx:60740, client unknown unknown failed.  Exception Table 'diva.os_groups_membership' doesn't exist   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQueryWithConnection(MySqlCommand cmd, MySqlConnection dbcon)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQuery(MySqlCommand cmd)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.Get(String field, String key)
   at OpenSim.Groups.GroupsService.GetAgentGroupMemberships(String RequestingAgentID, String AgentID)
   at OpenSim.Groups.GroupsModule.GetMembershipData(UUID agentID)
   at OpenSim.Region.ClientStack.LindenUDP.LLClientView.RefreshGroupMembership()
   at OpenSim.Region.Framework.Scenes.ScenePresence..ctor(IClientAPI client, Scene world, AvatarAppearance appearance, PresenceType type)
   at OpenSim.Region.Framework.Scenes.SceneGraph.CreateAndAddChildScenePresence(IClientAPI client, AvatarAppearance appearance, PresenceType type)
   at OpenSim.Region.Framework.Scenes.Scene.AddNewAgent(IClientAPI client, PresenceType type)
   at OpenSim.Region.ClientStack.LindenUDP.LLUDPServer.AddClient(UInt32 circuitCode, UUID agentID, UUID sessionID, IPEndPoint remoteEndPoint, AuthenticateResponse sessionInfo)
   at OpenSim.Region.ClientStack.LindenUDP.LLUDPServer.HandleUseCircuitCode(Object o)
```

And on the wifi web is something similar. once i click on "Manage Groups" it just gives out the following message:
Ooops!
The server you requested is overun by knomes! Find hippos quick!

The Server Log shows:
```
HandleRequest() threw exception MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'diva.os_groups_groups' doesn't exist
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQueryWithConnection(MySqlCommand cmd, MySqlConnection dbcon)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQuery(MySqlCommand cmd)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.Get(String where)
   at OpenSim.Data.MySQL.MySQLGroupsData.RetrieveGroups(String pattern)
   at OpenSim.Groups.GroupsService.FindGroups(String RequestingAgentID, String search)
   at Diva.Wifi.Services.GetGroupsList(Environment env)
   at Diva.Wifi.Services.GroupsManagementGetRequest(Environment env)
   at Diva.Wifi.WifiGroupsManagementGetHandler.Handle(String path, Stream requestData, IOSHttpRequest httpRequest, IOSHttpResponse httpResponse)
   at OpenSim.Framework.Servers.HttpServer.BaseHttpServer.HandleRequest(OSHttpRequest request, OSHttpResponse response)
```

Specs:
Diva Distro - diva-r09110 | (OpenSim 0.9.1.1) | Added 3/4/2020
MySql: MySQL8.0
Server: Windows Server 2016 Standard

Pure Vanilla Installation. No modification unless mentioned within the  Installation guide.

Tried troubleshooting:
- Reinstall of Diva
- Reinstall of MySQL (Various versions 6, 7, 8)
- Reinstall of whole Server 
- Regulär Things like driver and software updates

Is it possible to get a blank mysql dump to import manually?

Thanks a lot and best regards

**Comment by mdcowan** [comment]
I am having this issue as well. My avatar was able to login by disabling groups in MyWorld.ini. 

**Specs** 
Diva Distro - diva-r09110 | (OpenSim 0.9.1.1) | Added 3/4/2020
MySql: MySQL8.0
Server: Windows 10 Pro

```
UseCircuitCode handling from endpoint 192.168.1.1:60183, client unknown unknown failed.  Exception Table 'opensim.os_groups_membership' doesn't exist   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQueryWithConnection(MySqlCommand cmd, MySqlConnection dbcon)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.DoQuery(MySqlCommand cmd)
   at OpenSim.Data.MySQL.MySQLGenericTableHandler`1.Get(String field, String key)
   at OpenSim.Data.MySQL.MySQLGroupsData.RetrieveMemberships(String pricipalID)
   at OpenSim.Groups.GroupsService.GetAgentGroupMemberships(String RequestingAgentID, String AgentID)
   at OpenSim.Groups.GroupsServiceLocalConnectorModule.GetAgentGroupMemberships(String RequestingAgentID, String AgentID)
   at OpenSim.Groups.GroupsServiceHGConnectorModule.GetAgentGroupMemberships(String RequestingAgentID, String AgentID)
   at OpenSim.Groups.GroupsModule.GetMembershipData(UUID agentID)
   at OpenSim.Region.ClientStack.LindenUDP.LLClientView.RefreshGroupMembership()
   at OpenSim.Region.Framework.Scenes.ScenePresence..ctor(IClientAPI client, Scene world, AvatarAppearance appearance, PresenceType type)
   at OpenSim.Region.Framework.Scenes.SceneGraph.CreateAndAddChildScenePresence(IClientAPI client, AvatarAppearance appearance, PresenceType type)
   at OpenSim.Region.Framework.Scenes.Scene.AddNewAgent(IClientAPI client, PresenceType type)
   at OpenSim.Region.ClientStack.LindenUDP.LLClientView.Start()
   at OpenSim.Region.ClientStack.LindenUDP.LLUDPServer.AddClient(UInt32 circuitCode, UUID agentID, UUID sessionID, IPEndPoint remoteEndPoint, AuthenticateResponse sessionInfo)
   at OpenSim.Region.ClientStack.LindenUDP.LLUDPServer.HandleUseCircuitCode(Object o)
```

**Comment by compact729** [comment]
Same issue here... Have to disable groups just to make server useable. I would like to be able to use the groups function.

**Comment by enevold** [comment]
I got the same issue, anyone got this resolved?

br
EagleFX

**Comment by crista** [comment]
Please watch this video: https://www.youtube.com/watch?v=cz8PqnNvT1c
I explain and fix this issue shortly after minute 3.

**Comment by enevold** [comment]
Hi Crista
I can confirm it works according to your youtube video. by adding the tables manually, thanks
Br
EagleFX

**Comment by enevold** [comment]
I got another error on the startup of the 0.9110 version of D2, although I do not think that is has anything to do with the mysql, but an external service, not sure if this is an error on my side or the destination.

2021-02-16 19:43:12,276 ERROR - OpenSim.Framework.RestClient [REST CLIENT] Error fetching resource from server: http://metaverseink.com/cgi-bin/register.py?service=online&host=xxx.xxx.xxx.xxx&port=9001&secret=317c7225-504c-4045-8191-312f308d51d0 
System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
  at System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) [0x00146] in <6bc04dcac0a443ee834a449c98b8ed9d>:0 
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <6bc04dcac0a443ee834a449c98b8ed9d>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x00016] in <6bc04dcac0a443ee834a449c98b8ed9d>:0 
  at OpenSim.Framework.RestClient.Request (OpenSim.Framework.ServiceAuth.IServiceAuth auth) [0x000c1] in <f75c9f89ed9e45b892b0f10fda64e03e>:0

I removed the public ip in this error log for security reasons.

Br
EagleFX

**Comment by MovLab2** [comment]
I have this error also 
ERROR - OpenSim.Framework.RestClient [REST CLIENT] Error fetching resource from server: http://metaverseink.com/cgi-bin/register.py?service=online&host=xxx.xxx.xxx.xxx&port=9000&secret=317c7225-504c-4045-8191-312f308d51d0
sim still runs
